server:
  port: 8080
spring:
  resources:
    add-mappings: true
  banner:
    location: classpath:banner.txt
  data:
    mongodb:
      uri: mongodb+srv://root:sep11Jes170211@cluster0.85gyk.mongodb.net/dbjobs?retryWrites=true&w=majority
